<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Laki-laki</name>
   <tag></tag>
   <elementGuidId>6fd8cfff-3dcb-4bb2-abd0-5298422999a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gender']/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sc-gZMcBi.sc-kAzzGY.gBvxfY.sc-jtRfpW.evfBHa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e477328-4c4c-4d4f-8d9a-68524b4dad08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-custom</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;m&quot;,&quot;label&quot;:&quot;Laki-laki&quot;}</value>
      <webElementGuid>67ab2595-1c61-4df3-819b-8819a1892f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-gZMcBi sc-kAzzGY gBvxfY sc-jtRfpW evfBHa</value>
      <webElementGuid>6727abc2-03e4-4466-b8ad-a8b5b20d3be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Laki-laki</value>
      <webElementGuid>c0ee1a7e-0ece-40aa-a556-a96e464b9c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gender&quot;)/div[@class=&quot;sc-btzYZH hIOdwP&quot;]/div[@class=&quot;sc-lhVmIH bKaaGZ&quot;]/div[@class=&quot;sc-bYSBpT eMsBMS&quot;]/a[@class=&quot;sc-gZMcBi sc-kAzzGY gBvxfY sc-jtRfpW evfBHa&quot;]</value>
      <webElementGuid>b0c1e4e9-daf4-4cd5-a799-681caba39947</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gender']/div[2]/div/div/a</value>
      <webElementGuid>bc7a822e-64ef-4f9e-a54f-95fbca5d5eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Laki-laki')]</value>
      <webElementGuid>ff186fa9-50a7-44b7-989b-9d4eff2a4ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kelamin'])[1]/following::a[1]</value>
      <webElementGuid>58626ea3-e3db-467d-9b68-5ea21d88d767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Jenis Kelamin'])[1]/following::a[1]</value>
      <webElementGuid>740cb38b-f65c-45c7-b303-4371fab6e013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perempuan'])[1]/preceding::a[1]</value>
      <webElementGuid>4c91a270-5324-4322-ae12-e9f6b464d417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis kelamin wajib diisi'])[1]/preceding::a[2]</value>
      <webElementGuid>44abb1ff-6d58-4a49-acb0-e464545cdfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Laki-laki']/parent::*</value>
      <webElementGuid>e3e454aa-f237-460a-9679-fc84516542f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/a</value>
      <webElementGuid>24d85cbd-6c6f-4106-977e-dc14c868485e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Laki-laki' or . = 'Laki-laki')]</value>
      <webElementGuid>5e3dbade-6a14-49d8-87a4-32aa9fb5f9c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
