<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>account_icon</name>
   <tag></tag>
   <elementGuidId>0ce600d7-d003-4fe9-a938-d64d41348c7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popover-profile']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.sc-jzJRlG.dOVASO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1fe3df79-2a39-4f63-b822-bec21bf4274d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Kevan Dharma</value>
      <webElementGuid>75e7512e-b5df-496f-bb5d-04264b63b4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.sehatq.com/account/picture-empty/image-20220105-100017.png</value>
      <webElementGuid>8eb91e8f-1968-4832-aab2-959b6ff26577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>d66014d2-8698-4536-a4cf-c225afacea03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>2fd3aa84-5a0d-46e3-a54b-74a1d729f6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-jzJRlG dOVASO</value>
      <webElementGuid>21570454-61d5-4b1d-b644-4c82a4f09142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover-profile&quot;)/div[1]/img[@class=&quot;sc-jzJRlG dOVASO&quot;]</value>
      <webElementGuid>70336834-6608-456b-b15b-ad2530396b72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover-profile']/div/img</value>
      <webElementGuid>3372d91c-4448-4cb6-9cbe-371870a08ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Kevan Dharma']</value>
      <webElementGuid>83c0f4dd-68cc-4c90-abf4-482df6e04db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>eaeb9b55-3a05-44fc-9cd3-8629eb46775c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Kevan Dharma' and @src = 'https://static.sehatq.com/account/picture-empty/image-20220105-100017.png']</value>
      <webElementGuid>b22881da-ac70-42eb-8803-4ff945c49045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
