<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit Profil</name>
   <tag></tag>
   <elementGuidId>5190f089-c8d9-4de6-a9ff-3f2102c7235e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div[2]/div[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.chakra-link.css-1pwr2bt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c150fab1-72d3-48cc-8fda-6a83773eca61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-link css-1pwr2bt</value>
      <webElementGuid>cf081a43-0273-4e49-a103-9864e0aa7181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/profil/864247/detail/edit</value>
      <webElementGuid>334899eb-0164-4f89-9a3d-4f459a03f9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit Profil</value>
      <webElementGuid>eee9076a-7d80-45d2-8bb6-318113f5cd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-sz99ry&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;chakra-stack css-1hqazne&quot;]/div[@class=&quot;css-rslbfv&quot;]/a[@class=&quot;chakra-link css-1pwr2bt&quot;]</value>
      <webElementGuid>c046727b-9587-49f2-8be0-bfb090d03520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[2]/div[2]/div[2]/a</value>
      <webElementGuid>e1826fb5-922a-43e1-bbc1-5d4a49b9c707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit Profil')]</value>
      <webElementGuid>d5ca79fa-b113-4c18-976a-abfa31e0bb15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Profil'])[1]/following::a[7]</value>
      <webElementGuid>ae25d3ac-74ca-4c38-bbb7-f4a9f8ae94c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/following::a[8]</value>
      <webElementGuid>a8859b8f-3a42-4bf0-b870-0a8a49584cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit Profil']/parent::*</value>
      <webElementGuid>4aecac3d-bb2f-4b4b-bbb6-19f88ce6ae40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/profil/864247/detail/edit')]</value>
      <webElementGuid>786c9895-40da-484a-a7a5-030ed931739d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>a8ea13a0-9e87-4ffe-a9cf-6f89b5b964da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/profil/864247/detail/edit' and (text() = 'Edit Profil' or . = 'Edit Profil')]</value>
      <webElementGuid>cdeae377-34d5-43e3-8511-3699855ee40b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
